import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles } from "lucide-react";
import type { Recommendation } from "@/lib/carbon";

/**
 * Renders the **top N AI-prioritized recommendations**, ranked by
 * estimated carbon-reduction impact (largest first).
 * Input is assumed pre-generated by `generateRecommendations`, which already
 * sorts descending — we slice defensively in case callers pass an unsorted list.
 */
export function TopRecommendations({
  recommendations,
  limit = 3,
}: {
  recommendations: Recommendation[];
  limit?: number;
}) {
  const top = [...recommendations]
    .sort((a, b) => b.estimatedSavingKg - a.estimatedSavingKg)
    .slice(0, limit);

  if (top.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>AI recommendations</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">
          Your habits look great — no high-impact changes to suggest right now.
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center gap-2">
        <Sparkles className="size-4 text-primary" aria-hidden />
        <CardTitle>Top {top.length} AI-prioritized actions</CardTitle>
      </CardHeader>
      <CardContent className="grid sm:grid-cols-3 gap-3">
        {top.map((r, i) => (
          <div key={`${r.category}-${i}`} className="rounded-lg border border-border p-4">
            <div className="flex items-center justify-between mb-2">
              <Badge variant="secondary" className="capitalize">
                {r.category}
              </Badge>
              <span className="text-xs text-primary font-semibold">
                ~{r.estimatedSavingKg} kg/mo
              </span>
            </div>
            <h4 className="font-medium leading-snug">{r.title}</h4>
            <p className="text-xs text-muted-foreground mt-1">{r.detail}</p>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
